version: "3.3"

services:
  db:
    image: mariadb:latest
    volumes:
      - ./db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mautic
      - MYSQL_USER=mautic
      - MYSQL_PASSWORD=secret

  mautic:
    container_name: mautic
    image: mautic/mautic:v3
    volumes:
      - ./mautic_data:/var/www/html
    environment:
      - MAUTIC_DB_HOST=db:3306
      - MAUTIC_DB_USER=mautic
      - MAUTIC_DB_PASSWORD=secret
      - MAUTIC_DB_NAME=mautic
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8200:80"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=mautic
      - PMA_PASSWORD=secret
    networks:
      - default
    ports:
      - "8080:80"

volumes:
  db_data:
  mautic_data:
